{
  humbert_degree.m
  humbert_surfaces.m
  humbert_interpolation.m
  satake_humbert.m
  Level1Satake
  {
    humbert_01.m
    humbert_04.m
    humbert_05.m
    humbert_08.m
    humbert_09.m
    humbert_12.m
    humbert_13.m
    humbert_16.m
    humbert_17.m
    humbert_20.m
    humbert_21.m
  }
  Level2Rosenhain
  {
    humbert_01.m
    humbert_04.m
    humbert_05.m
    humbert_08.m
    humbert_09.m
    humbert_12.m
    humbert_13.m
    humbert_16.m
    humbert_17.m
    humbert_20.m
  }
  Level2Theta
  {
    humbert_01.m
    humbert_04.m
    humbert_05.m
    humbert_08.m
    humbert_09.m
    humbert_12.m
    humbert_13.m
    humbert_16.m
    humbert_17.m
    humbert_20.m
    humbert_24.m
    humbert_28.m
    humbert_32.m
    humbert_36.m
    humbert_40.m
    humbert_44.m
    humbert_48.m
    humbert_52.m
    humbert_56.m
    humbert_60.m
    humbert_68.m
  }
  DB
  {
    +DBSrfRM.spec
  }
}
